// <auto-generated />
using System;
using FitrahDataAccess.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FitrahDataAccess.Migrations
{
    [DbContext(typeof(FitrahContext))]
    [Migration("20240416020956_AddRecapFitrah")]
    partial class AddRecapFitrah
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FitrahDataAccess.Models.Account", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(300)
                        .IsUnicode(false)
                        .HasColumnType("varchar(300)");

                    b.HasKey("Username")
                        .HasName("PK__Accounts__536C85E5163BCFF6");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("FitrahDataAccess.Models.History", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AmilUsername")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("FidiyaMoney")
                        .HasColumnType("money");

                    b.Property<decimal?>("FidiyaRice")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("FitrahMoney")
                        .HasColumnType("money");

                    b.Property<decimal?>("FitrahRice")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("InfaqMoney")
                        .HasColumnType("money");

                    b.Property<decimal?>("InfaqRice")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("MaalMoney")
                        .HasColumnType("money");

                    b.Property<decimal?>("MaalRice")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("MuzakkiName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Code")
                        .HasName("PK__Historie__A25C5AA6C40AB357");

                    b.HasIndex("AmilUsername");

                    b.ToTable("Histories");
                });

            modelBuilder.Entity("FitrahDataAccess.Models.Recap", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Date");

                    b.ToTable("Recaps");
                });

            modelBuilder.Entity("FitrahDataAccess.Models.History", b =>
                {
                    b.HasOne("FitrahDataAccess.Models.Account", "AmilUsernameNavigation")
                        .WithMany("Histories")
                        .HasForeignKey("AmilUsername")
                        .IsRequired()
                        .HasConstraintName("FK_Histories_Accounts");

                    b.Navigation("AmilUsernameNavigation");
                });

            modelBuilder.Entity("FitrahDataAccess.Models.Account", b =>
                {
                    b.Navigation("Histories");
                });
#pragma warning restore 612, 618
        }
    }
}
